### ISSUE TITLE
Totem spawn doesn't work

### ISSUE THREAD

**Issue by luizsusin** [Auxilor/EcoBosses#24]
**Describe the bug**
Spawning bosses using Totems doesn't work.

**To Reproduce**
1. Build the totem.

**Expected behavior**
Totems should spawn the boss and remove the totem itself.

**Server Information (please complete the following information):**
- Version: git-Purpur-1564 (MC: 1.18.1)
- Version of plugin and eco: EcoBosses 8.5.0; Eco 6.25.2

**Additional context**
WillFP forgot to call BossSpawnEvent on Totem Handler.
I've made a really simple PR (#19) fixing it, but no attention has been given in the past 16 days.

**Comment by WillFP** [comment]
Fixed in next version
