### ISSUE TITLE
ModelEngine Support

### ISSUE THREAD

**Issue by EwansXD** [Auxilor/EcoBosses#29]
**Is your feature request related to a problem? Please describe.**
Currently you can only use vanilla mobs for bosses, I believe adding modelengine support world elevate the plugin to the next level allowing for infinite mob designs and a lot more customizability.

**Describe the solution you'd like**
Hooking into the API for ModelEngine to be able to use custom models as bosses.

**Describe alternatives you've considered**
There aren't any.

**Additional context**
Will need to be able to set states like the default, walking & then skill based ones.
API Link: https://github.com/elBukkit/ModelEngineSpawner

**Comment by Opalinium** [comment]
+1

**Comment by borovniki** [comment]
+1   Allso an itemsadder support for the new custom entity option would be great.
