### ISSUE TITLE
Piglin Bosses turn into Zombie Pigmen

### ISSUE THREAD

**Issue by Bossimal** [Auxilor/EcoBosses#36]
When in the over world piglin bosses turn into zombie pigmen after 15 seconds. I know these is a vanilla feature but I was wondering if you could add a toggle to enable/disable this from happening. 

I looked through the spigot java docs and I think this is the method you would use https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/PiglinAbstract.html#setImmuneToZombification(boolean)

**To Reproduce**
1. Create a piglin_brute boss 
2. Spawn the boss in the over world 
3. Wait 15 seconds and it will transform into a zombie pigmen 

**Expected behavior**
When transform option is enabled in the config it would turn into a zombie pigmen
When transform option is disabled in the config it wouldn't turn into a pigmen 

**Server Information**
Server Version: 1.18.2 paper
Eco Version: 6.33.0
EcoBosses Version:  8.22.0

**Comment by PrimalPower** [comment]
This also happens with drowning husks/zombies, curing zombie villagers, freezing skeletons, zombifying hoglins/piglin brutes/piglins
