### ISSUE TITLE
bosses do not spawn out of eggs if the egg is used with a dispenser

### ISSUE THREAD

**Issue by insert-usernamehere** [Auxilor/EcoBosses#40]
**Describe the bug**
Trying to use dispensers to spawn bosses as a way to spawn bosses in randomly; generated structures but I have run into an issue which is that the plugin seems to not detect the spawn eggs as boss spawn eggs. So instead the dispenser spawns (in this case) an evoker named steel golem spawn egg.

**To Reproduce**
1. give yourself an ecoboss spawn egg
2. place the spawn egg in a dispense
3. trigger the dispenser
4. observe as it does not spawn a boss

**Expected behavior**
The expected behavior is for the dispenser to spawn a boss that works completely

**Screenshots**
![2022-05-29_10 29 24](https://user-images.githubusercontent.com/29443173/170874453-d66756ac-a17c-4e6c-b4ab-20ef3fba5dde.png)

**Server Information**
- server version: git-Purpur-1609 (MC: 1.18.2)*
- eco: 6.35.4
- ecobosses: 8.26.0

**Additional context**
To test this I used the default config

**Comment by DaRacci** [comment]
This seems to be mostly an issue with events as the respective event that should make this easy doesn't ever use the DISPENSE_EGG condition which means it'd have to track a number of things to do this.
