### ISSUE TITLE
Jitpack builds failing

### ISSUE THREAD

**Issue by PikaMug** [Auxilor/EcoBosses#41]
**Describe the bug**
No releases of EcoBosses are available via Jitpack (6.8.0 built but seems to have invalid artifact descriptor).

**To Reproduce**
1. Go to jitpack.com
2. Enter project and click 'Look up'
3. See failed builds

**Expected behavior**
At least one recent release should be available.

**Additional context**
My guess would be that Jitpack doesn't really support Java 17 even with your jitpack.yml workaround. If it's truly required, consider submitting your project to something like CodeMC if you're unable to host your own Maven repository.

**Comment by DaRacci** [comment]
This can be closed now

**Comment by DaRacci** [comment]
> @DaRacci Why? Current builds on Jitpack don't produce an artifact (missing core-plugin).
My PR that fixes this was merged so next time there is a version bump it'll be working

**Comment by PikaMug** [comment]
How did I not see that. Thanks!
